### ISSUE TITLE
Intune-Set-PrimaryUser

### ISSUE THREAD

**Issue by wisper1977** [Mr-Tbone/Intune#2]
I do not know if it something I am doing or not, but when i run this in Azure Automation, I get the following error:

`The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to connect to Graph, with error: Cannot bind parameter 'AccessToken'. Cannot convert the "eyJ0eXAiOiJKV1QiLCJub25jZSI6Imw0R21uMDZudC1YdVRuZkFKQ0ZON3UwOEdESmZUVzB6MnFmVTB1TTVZX2siLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20vIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvODc2NDIyNTgtNzYzMS00NDdmLTg1ZGYtYjIzZjFhMTAzNDM4LyIsImlhdCI6MTY5MjI5NTA3NywibmJmIjoxNjkyMjk1MDc3LCJleHAiOjE2OTIzODE3NzcsImFpbyI6IkUyRmdZR2hXNVVsOTNGeDZRZEt3WWZVaEcrRm5BQT09IiwiYXBwX2Rpc3BsYXluYW1lIjoiYXV0b21hdGlvbiIsImFwcGlkIjoiOTkxNTRhYWItOTc4Yi00OTQyLTlmYWUtZmYyNjUyYzZjZmZkIiwiYXBwaWRhY3IiOiIyIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvODc2NDIyNTgtNzYzMS00NDdmLTg1ZGYtYjIzZjFhMTAzNDM4LyIsImlkdHlwIjoiYXBwIiwib2lkIjoiN2MzZTI5Y2ItZmY0MC00NjA4LWExNjItNzdhZGQ0OThiODg5IiwicmgiOiIwLkFSc0FXQ0praHpGMmYwU0YzN0lfR2hBME9BTUFBQUFBQUFBQXdBQUFBQUFBQUFEWUFBQS4iLCJyb2xlcyI6WyJEZXZpY2VNYW5hZ2VtZW50TWFuYWdlZERldmljZXMuUmVhZC5BbGwiLCJVc2VyLlJlYWQuQWxsIiwiRGV2aWNlTWFuYWdlbWVudE1hbmFnZWREZXZpY2VzLlJlYWRXcml0ZS5BbGwiLCJBdWRpdExvZy5SZWFkLkFsbCJdLCJzdWIiOiI3YzNlMjljYi1mZjQwLTQ2MDgtYTE2Mi03N2FkZDQ5OGI4ODkiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiTkEiLCJ0aWQiOiI4NzY0MjI1OC03NjMxLTQ0N2YtODVkZi1iMjNmMWExMDM0MzgiLCJ1dGkiOiJzMjNPampjRUwwYTJjWml6M2JTMEFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyIwOTk3YTFkMC0wZDFkLTRhY2ItYjQwOC1kNWNhNzMxMjFlOTAiXSwieG1zX3RjZHQiOiIxNDg1NzE3MTYzIn0.d0wo28AOvJjfzFePD75O9zi6CKR0q2j8DflMoriFQzCwkVQcUkiuL5mv2dg46WPWlCOYr5uDGBNdmU-z6Ci9rjSG14acIXZ-zF2E9gnO6H4sJ0C-CW-gDutIj2In_D5I1dVTVoaJMqRIVPiYENEpAukXjcyfgCafsJwyYDZaL9Bs3W9dkg8UX3A2AvPq4_3BCivm7wfcbfuZd1oIhICfpuB8CkTfW8JPt9Yxifw6Fv2r6-CAWM5QZztliBJHgY5wQIE9Lb1Vq8MnT9tKJIGl_YMjVVbg508owscBRin15F4_5AhYeQeZx5eA8s1II7tRlYFux6BE8UWusaF8KcItQw" value of type "System.String" to type "System.Security.SecureString".`

Any help with this would be greatful.

**Comment by ecr80** [comment]
hey i managed to solve this by modifying the connect -mgGraph -AccessToken line. it goes like this:

Connect-mgGraph -AccessToken ($accessToken |ConvertTo-SecureString -AsPlainText -Force)

After that it ran fine.

**Comment by Mr-Tbone** [comment]
Thanks for finding a fix for this.
I have updated the script.
